server:
  port: 8080
zuul:
  routes:
    user:
      path: /user/**
      url: http://user-edge-servie:8001/user/
    course:
      path: /course/**
      url: http://course-edge-service:9001/course/
