server:
  port: 8080
zuul:
  routes:
    user:
      path: /user/**
      url: http://user-thrift-servie:8000/user/
    course:
      path: /course/**
      url: http://course-dubbo-service:9000/course/
