apiVersion: v1
kind: Service
metadata:
  labels:
    app: course-service
  name: course-service
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: course-service
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: course-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: hub.dreams.com/dreams-micro-service/course-dubbo-service:1.1-SNAPSHOT
        ports:
        - containerPort: 9000
      - name: course-edge-service
        image: hub.dreams.com/dreams-micro-service/course-edge-service:1.1-SNAPSHOT
        ports:
        - containerPort: 9001

